
version: '3.8'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: api
    ports:
      - "5148:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app
    working_dir: /app
    command: ["dotnet", "run", "--urls", "http://*:80"]
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/caioocon/Downloads/ProjetoApi/ProjetoApi/prometheus.yml:/etc/prometheus/prometheus.yml

    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
        - prometheus