
global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["projetoapi:8080"] 
  - job_name: "docker"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
          